# Pre-commit configuration for Go projects
# Repo: https://github.com/tekwizely/pre-commit-golang
# All hooks are from this repo unless specified otherwise
repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
    - id: go-test-repo-mod
      args: ["-v"]
    - id: go-build-repo-mod
    - id: go-mod-tidy-repo
