name: ecommerce
version: '1.0.0'
config-version: 2

profile: ecommerce

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ecommerce:
    staging:
      +materialized: view
    marts:
      +materialized: table
